// Date: 7/29/2013 5:39:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package cloudioa.mymod.platipusmod.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class platypusmodel extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Fr;
    ModelRenderer Fl;
    ModelRenderer Br;
    ModelRenderer Bl;
    ModelRenderer head;
    ModelRenderer beak1;
    ModelRenderer beek2;
 
  
  public platypusmodel()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-3F, 0F, 0F, 6, 3, 6);
      Body.setRotationPoint(0F, 19F, -2F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Fr = new ModelRenderer(this, 24, 3);
      Fr.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      Fr.setRotationPoint(-2.5F, 22F, -1.5F);
      Fr.setTextureSize(64, 32);
      Fr.mirror = true;
      setRotation(Fr, 0F, 0F, 0F);
      Fl = new ModelRenderer(this, 28, 3);
      Fl.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      Fl.setRotationPoint(2.5F, 22F, -1.5F);
      Fl.setTextureSize(64, 32);
      Fl.mirror = true;
      setRotation(Fl, 0F, 0F, 0F);
      Br = new ModelRenderer(this, 24, 0);
      Br.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      Br.setRotationPoint(-2.5F, 22F, 3.5F);
      Br.setTextureSize(64, 32);
      Br.mirror = true;
      setRotation(Br, 0F, 0F, 0F);
      Bl = new ModelRenderer(this, 28, 0);
      Bl.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      Bl.setRotationPoint(2.5F, 22F, 3.5F);
      Bl.setTextureSize(64, 32);
      Bl.mirror = true;
      setRotation(Bl, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 9);
      head.addBox(-3F, -1F, -3F, 6, 3, 3);
      head.setRotationPoint(0F, 19F, -2F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0.0174533F, 0F, 0F);
      beak1 = new ModelRenderer(this, 32, 0);
      beak1.addBox(-2.5F, 0F, -2F, 5, 1, 2);
      beak1.setRotationPoint(0F, 20F, -5F);
      beak1.setTextureSize(64, 32);
      beak1.mirror = true;
      setRotation(beak1, 0F, 0F, 0F);
      beek2 = new ModelRenderer(this, 35, 4);
      beek2.addBox(-1.5F, -0.5F, -1F, 3, 1, 1);
      beek2.setRotationPoint(0F, 20.5F, -7F);
      beek2.setTextureSize(64, 32);
      beek2.mirror = true;
      setRotation(beek2, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
    setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Body.render(par7);
    Fr.render(par7);
    Fl.render(par7);
    Br.render(par7);
    Bl.render(par7);
    head.render(par7);
    beak1.render(par7);
    beek2.render(par7);
  }
   
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
   this.Fl.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 2.0F * par2 * 0.5F;
   this.Fl.rotateAngleY = 0.0F;
   this.Fr.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 2.0F * par2 * 0.5F;
   this.Fr.rotateAngleY = 0.0F;
   this.Bl.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 2.0F * par2 * 0.5F;
   this.Bl.rotateAngleY = 0.0F;
   this.Br.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 2.0F * par2 * 0.5F;
   this.Br.rotateAngleY = 0.0F;
   
		   
		   
		   
		   
		   
		   
		   
		   
		   
		   
		   
  }

}
